apiVersion: v1
kind: Namespace
metadata:
  name: mig-ui-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mig-ui-plugin
  namespace: mig-ui-plugin
  labels:
    app: mig-ui-plugin
    app.kubernetes.io/component: mig-ui-plugin
    app.kubernetes.io/instance: mig-ui-plugin
    app.kubernetes.io/part-of: mig-ui-plugin
    app.openshift.io/runtime-namespace: mig-ui-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mig-ui-plugin
  template:
    metadata:
      labels:
        app: mig-ui-plugin
    spec:
      containers:
        - name: mig-ui-plugin
          image: quay.io/rawagner/mig-ui-plugin
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          args:
            - "--ssl"
            - "--cert=/var/serving-cert/tls.crt"
            - "--key=/var/serving-cert/tls.key"
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: mig-ui-plugin
  namespace: mig-ui-plugin
  labels:
    app: mig-ui-plugin
    app.kubernetes.io/component: mig-ui-plugin
    app.kubernetes.io/instance: mig-ui-plugin
    app.kubernetes.io/part-of: mig-ui-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: mig-ui-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: mig-ui-plugin
spec:
  displayName: "Mig UI Plugin"
  service:
    name: mig-ui-plugin
    namespace: mig-ui-plugin
    port: 9001
    basePath: "/"
